import type {Metadata} from 'next'
import './clash-display.css'
import './globals.css'
import {defaultUrl} from '@/lib/constants'
import {Toaster} from '@/components/ui/sonner'
import {DialogsProvider} from '@/components/providers/dialog-provider'

export const metadata: Metadata = {
	metadataBase: new URL(defaultUrl),
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className="font-ClashDisplay">
				<DialogsProvider>
					<div className="[&>main]:min-h-svh w-full mx-auto max-w-[600px] px-6 [&>main]:py-6">
						{children}
					</div>
				</DialogsProvider>

				<Toaster />
			</body>
		</html>
	)
}
